version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse:6.4.1-ubuntu
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["80:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://concourse.jsp.kr
      CONCOURSE_ADD_LOCAL_USER: jsp:jsp
      CONCOURSE_MAIN_TEAM_LOCAL_USER: jsp
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
#      CONCOURSE_WORK_DIR: /Users/jsp/HashiCorp/snapshot/vault-secure-ci-pipeline/worker
  
